### ISSUE TITLE
CryptonightV7

### ISSUE THREAD

**Issue by Deadly-M** [anadventureisu/cast-xmr-ui#8]
Hi
Thanks for your project, helping me stay online!
but could you add a switch for CryptonightV7, thats the --algo -1,0,1 switch
Thanks.

**Comment by anadventureisu** [comment]
Yes, I’m working on adding a “generic options” field so you can add extra options as they’re added to the miner.

**Comment by Deadly-M** [comment]
Ah , nice
that way you wont need to update it so much.
Thanks.

**Comment by anadventureisu** [comment]
Fixed in Release 0.9.4 https://github.com/anadventureisu/cast-xmr-ui/releases/tag/0.9.4

**Comment by polofitted007** [comment]
In the new filed, how should be input the command.  --algo 1 or jsut algo 1?

edit:  works with the "--algo 1"
